#PULLING an ALPINE IMAGE (LESS IN SIZE)
FROM node:18-alpine

#INSTALLING PNPM
RUN npm i -g pnpm

#CHANGING THE DIRECTORY
WORKDIR /app

#COPYING THE NECESSARY FILES
COPY package.json pnpm-lock.yaml ./

#RUNNING `PNPM INSTALL` TO INSTALL THE DEPENDENCIES
RUN pnpm install

#COPYING THE FILES TO THE APP DIRECTORY
COPY . .

#RUNNING THE APPLICATION INSIDE THE CONTAINER
CMD ["pnpm", "start"]