export const products = {
  data: [
    {
      productName: "Flow CV",
      category: "resume",
      image: "https://bit.ly/3YnFYBJ",
      link: "https://flowcv.com/",
    },
    {
      productName: "Reactive Resume",
      category: "resume",
      image: "https://bit.ly/3YKPTRr",
      link: "https://rxresu.me/",
    },
    {
      productName: "Poet.so",
      category: "tweet",
      image: "https://bit.ly/3IiqJUM",
      link: "https://poet.so/",
    },
    {
      productName: "Bitly [Url_shortner]",
      category: "tools",
      image: "https://bit.ly/3xnfdRH",
      link: "https://bitly.com/",
    },
    {
      productName: "Contributors image generator",
      category: "tools",
      image: "https://bit.ly/3Z1Fz7L",
      link: "https://contrib.rocks/",
    },
    {
      productName: "Remote OK",
      category: "remote",
      image: "https://bit.ly/3RQAMDP",
      link: "hhttps://remoteok.com/",
    },
    {
      productName: "Angel.co",
      category: "remote",
      image: "https://bit.ly/3E48AHM",
      link: "https://angel.co/",
    },
    {
      productName: "Remotive",
      category: "remote",
      image:
        "https://remotive.com/remotive_website_layout/static/src/img/favicon.ico",
      link: "https://remotive.com/",
    },
    {
      productName: "Himalayas",
      category: "remote",
      image: "https://bit.ly/3RXjh4H",
      link: "https://himalayas.app/",
    },
    {
      productName: "We Work Remotely",
      category: "remote",
      image: "https://bit.ly/3jSH49u",
      link: "https://weworkremotely.com/",
    },
    {
      productName: "Remote.co",
      category: "remote",
      image:
        "https://remoteco.s3.amazonaws.com/wp-content/uploads/2017/02/retina_favicon_32.png",
      link: "https://remote.co/",
    },
    {
      productName: "JustRemote",
      category: "remote",
      image: "https://bit.ly/3I28PEK",
      link: "https://justremote.co/",
    },
    {
      productName: "Arc.dev",
      category: "remote",
      image: "https://bit.ly/3Yq5Lcp",
      link: "https://arc.dev/",
    },
    {
      productName: "Skip The Drive",
      category: "remote",
      image:
        "https://skipthedrive.b-cdn.net/wp-content/uploads/2023/02/favicon_32c.png",
      link: "https://www.skipthedrive.com/",
    },
    {
      productName: "Jobspresso",
      category: "remote",
      image: "https://bit.ly/3HTbQqE",
      link: "https://jobspresso.co/",
    },
    {
      productName: "Working No Mads",
      category: "remote",
      image: "https://www.workingnomads.com/static/jobs/assets/favicon.ico",
      link: "https://www.workingnomads.com/",
    },
    {
      productName: "Pika Style",
      category: "tweet",
      image: "https://bit.ly/3jQ6g0b",
      link: "https://pika.style/templates/tweet-image",
    },
    {
      productName: "Code Beautify",
      category: "code",
      image: "https://bit.ly/3xhLeL2",
      link: "https://codebeautify.org/code-to-image-converter",
    },
    {
      productName: "Carbon Now",
      category: "code",
      image: "https://bit.ly/3YIet5A",
      link: "https://carbon.now.sh/",
    },
    {
      productName: "Ray.so",
      category: "code",
      image: "https://bit.ly/40HNhpc",
      link: "https://ray.so/",
    },
    {
      productName: "100L5",
      category: "code",
      image: "https://bit.ly/40N3r0C",
      link: "https://10015.io/tools/code-to-image-converter",
    },
    {
      productName: "ReadMe Generator",
      category: "tools",
      image: "https://bit.ly/3IjJ97J",
      link: "https://github-profile-readme-generator-47w21mt0m-rahuldkjain.vercel.app/",
    },
    {
      productName: "LeetHub",
      category: "tools",
      image: "https://bit.ly/3lv6L0h",
      link: "https://chrome.google.com/webstore/detail/leethub/aciombdipochlnkbpcbgdpjffcfdbggi?hl=en",
    },
    {
      productName: "AdBlock",
      category: "tools",
      image: "https://bit.ly/3K3rqmo",
      link: "https://chrome.google.com/webstore/detail/adblock-%E2%80%94-best-ad-blocker/gighmmpiobklfepjocnamgkkbiglidom",
    },
    {
      productName: "Grammarly",
      category: "tools",
      image: "https://bit.ly/3xg1goX",
      link: "https://app.grammarly.com/",
    },
    {
      productName: "Wordtune",
      category: "tools",
      image:
        "https://uploads-ssl.webflow.com/5f7e0f9d75fee6f6f546df46/62c18c97efce291098cf0656_Favicon.png",
      link: "https://www.wordtune.com/",
    },
    {
      productName: "Code Pen",
      category: "tools",
      image: "https://bit.ly/2I9FxYw",
      link: "https://codepen.io/",
    },
    {
      productName: "Toptal",
      category: "remote",
      image: "https://frontier-assets.toptal.com/c4a9fd60eec9d204fb7d.png",
      link: "https://www.toptal.com/",
    },
    {
      productName: "DevSnap",
      category: "remote",
      image: "https://bit.ly/3JXDA02",
      link: "https://devsnap.me/",
    },
    {
      productName: "Up Work",
      category: "remote",
      image: "https://www.upwork.com/favicon.ico",
      link: "https://www.upwork.com/",
    },
    {
      productName: "PNGWING",
      category: "tools",
      image: "https://bit.ly/3xgMy0L",
      link: "https://www.pngwing.com/",
    },
    {
      productName: "Readme.so",
      category: "tools",
      image: "https://readme.so/readme.png",
      link: "https://readme.so/editor",
    },
    {
      productName: "GPRM [Readme]",
      category: "tools",
      image: "https://gprm.itsvg.in/logo.png",
      link: "https://gprm.itsvg.in/",
    },
    {
      productName: "Hired.com",
      category: "remote",
      image: "https://bit.ly/3EjH1up",
      link: "https://hired.com/",
    },
    {
      productName: "Jsonlint.com",
      category: "tools",
      image: "https://jsonlint.com/favicon.ico",
      link: "https://jsonlint.com",
    },
    {
      productName: "Figma.com",
      category: "tools",
      image: "https://static.figma.com/app/icon/1/favicon.png",
      link: "https://www.figma.com/",
    },
    {
      productName: "smalldev",
      category: "tools",
      image: "https://smalldev.tools/favicon.png",
      link: "https://smalldev.tools",
    },
    {
      productName: "futurepedia",
      category: "tools",
      image: "https://www.futurepedia.io/futurepedia-small.svg",
      link: "https://www.futurepedia.io/",
    },
    {
      productName: "jsonformatter",
      category: "tools",
      image: "https://jsonformatter.org/img/favicon.png",
      link: "https://jsonformatter.org/",
    },
    {
      productName: "Kick Resume",
      category: "resume",
      image: "https://bit.ly/3Slt9FG",
      link: "https://www.kickresume.com/en/",
    },
    {
      productName: "ResumeMaker.AI",
      category: "resume",
      image: "https://bit.ly/3XNlQHP",
      link: "https://resumaker.ai/",
    },
    {
      productName: "Resumai",
      category: "resume",
      image: "https://bit.ly/3IKg8SK",
      link: "https://www.resumai.com/",
    },
    {
      productName: "Rezi.AI",
      category: "resume",
      image: "https://bit.ly/41lWvYv",
      link: "https://www.rezi.ai/",
    },
    {
      productName: "Bugcrowd",
      category: "ethical",
      image: "https://bit.ly/3xQvqz9",
      link: "https://www.bugcrowd.com/",
    },
    {
      productName: "Hackthisiste",
      category: "ethical",
      image: "https://bit.ly/3xQRwl9",
      link: "https://www.hackthissite.org/",
    },
    {
      productName: "Hackerone",
      category: "ethical",
      image: "https://bit.ly/3KEJMdE",
      link: "https://hackerone.com/",
    },
    {
      productName: "m0chan",
      category: "ethical",
      image: "https://bit.ly/3Y3S0Pz",
      link: "https://m0chan.github.io/",
    },
    {
      productName: "Hacker101",
      category: "ethical",
      image: "https://bit.ly/3IpQ5iu",
      link: "https://www.hacker101.com/",
    },
    {
      productName: "Tryhackme",
      category: "ethical",
      image: "https://bit.ly/3SsfjS2",
      link: "https://tryhackme.com/",
    },
    {
      productName: "cve mitre",
      category: "ethical",
      image: "https://bit.ly/3SwuV6V",
      link: "https://cve.mitre.org/",
    },
    {
      productName: "Hackthebox",
      category: "ethical",
      image: "https://bit.ly/3ZdEtGk",
      link: "https://www.hackthebox.com/",
    },
    {
      productName: "owasp",
      category: "ethical",
      image: "https://bit.ly/3m4MVcC",
      link: "https://owasp.org/",
    },
    {
      productName: "crackstation",
      category: "ethical",
      image: "https://bit.ly/3ITIKZZ",
      link: "https://crackstation.net/",
    },
    {
      productName: "owasp cheetsheet",
      category: "ethical",
      image: "https://bit.ly/3KzvhI7",
      link: "https://cheatsheetseries.owasp.org/",
    },
    {
      productName: "Cryptohack",
      category: "ethical",
      image: "https://bit.ly/3Z0vQiB",
      link: "https://cryptohack.org/",
    },
    {
      productName: "OSINT Framework",
      category: "ethical",
      image: "",
      link: "https://osintframework.com/",
    },
    {
      productName: "Colorhunt",
      category: "web",
      image: "https://bit.ly/3Kz550h",
      link: "https://colorhunt.co/",
    },
    {
      productName: "Sitepoint",
      category: "web",
      image: "https://bit.ly/3IyNvXB",
      link: "https://www.sitepoint.com/",
    },
    {
      productName: "css tricks",
      category: "web",
      image: "https://bit.ly/3kt5mal",
      link: "https://css-tricks.com/",
    },
    {
      productName: "web designer Depot",
      category: "web",
      image: "https://bit.ly/3KBrji4",
      link: "https://www.webdesignerdepot.com/",
    },
    {
      productName: "Themeforest",
      category: "web",
      image: "https://bit.ly/3m0ZW6N",
      link: "https://themeforest.net/",
    },
    {
      productName: "CSS Gradient",
      category: "web",
      image: "https://bit.ly/3EGBUV9",
      link: "https://cssgradient.io/",
    },
    {
      productName: "Get Waves",
      category: "web",
      image: "https://bit.ly/3IUfGSg",
      link: "https://getwaves.io/",
    },
    {
      productName: "CodeSandBox",
      category: "web",
      image: "https://bit.ly/3KESoB0",
      link: "https://codesandbox.io/",
    },
    {
      productName: "Mesh Gradient",
      category: "web",
      image: "https://bit.ly/3KUNHDt",
      link: "https://products.ls.graphics/mesh-gradients/",
    },
    {
      productName: "Illustrations",
      category: "web",
      image: "https://bit.ly/3ZhaVra",
      link: "https://www.freepik.com/vectors/illustrations",
    },
    {
      productName: "Device Shots",
      category: "web",
      image: "https://bit.ly/3m8mQta",
      link: "http://deviceshots.com/",
    },
    {
      productName: "Collors",
      category: "web",
      image: "https://bit.ly/3kq0zq4",
      link: "https://coolors.co/",
    },
    {
      productName: "Dev Docs",
      category: "web",
      image: "https://bit.ly/3StX6TY",
      link: "https://devdocs.io/",
    },
    {
      productName: "Splide js",
      category: "web",
      image: "https://bit.ly/3StX6TY",
      link: "https://splidejs.com/",
    },
    {
      productName: "babel js",
      category: "web",
      image: "https://bit.ly/3xPrHBY",
      link: "https://babeljs.io/",
    },
    {
      productName: "js fiddle",
      category: "web",
      image: "https://bit.ly/3ktrJwk",
      link: "https://jsfiddle.net/",
    },
    {
      productName: "box-shadow",
      category: "web",
      image: "https://bit.ly/3ITuAIg",
      link: "https://box-shadow.dev/",
    },
    {
      productName: "unminify",
      category: "web",
      image: "https://bit.ly/3Y32LSi",
      link: "https://unminify.com/",
    },
    {
      productName: "flaticon",
      category: "web",
      image: "https://bit.ly/3ktuJZG",
      link: "https://www.flaticon.com/",
    },
    {
      productName: "veed",
      category: "tools",
      image: "https://bit.ly/3ZDEfbJ",
      link: "https://www.veed.io/",
    },
    {
      productName: "tiny cloud",
      category: "tools",
      image: "https://bit.ly/3Z4tv68",
      link: "https://www.tiny.cloud/",
    },
    {
      productName: "news api",
      category: "tools",
      image: "https://bit.ly/3xSWwG8",
      link: "https://newsapi.org/account",
    },
    {
      productName: "wetransfer",
      category: "tools",
      image: "https://bit.ly/3krko0a",
      link: "https://wetransfer.com/",
    },
    {
      productName: "photopea",
      category: "tools",
      image: "https://bit.ly/3YZGSVi",
      link: "https://www.photopea.com/",
    },
    {
      productName: "theuselessweb",
      category: "tools",
      image: "https://bit.ly/3Z1kMBI",
      link: "https://theuselessweb.com/",
    },
    {
      productName: "imgbb",
      category: "tools",
      image: "https://bit.ly/3KCM6BJ",
      link: "https://imgbb.com/",
    },
    {
      productName: "avatars dicebear",
      category: "tools",
      image: "https://bit.ly/3Y01SKi",
      link: "https://avatars.dicebear.com/",
    },
    {
      productName: "pfpmaker",
      category: "tools",
      image: "https://bit.ly/3ZmRM7m",
      link: "https://pfpmaker.com/",
    },
    {
      productName: "jwt",
      category: "tools",
      image: "https://bit.ly/3XWzjx3",
      link: "https://jwt.io/",
    },
    {
      productName: "yandex",
      category: "tools",
      image: "https://bit.ly/3ZnKUX1",
      link: "https://yandex.com/",
    },
  ],
};
